// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package controller

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson455788a0DecodeWsTermInternalController(in *jlexer.Lexer, out *WindowSize) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "high":
			out.High = int(in.Int())
		case "width":
			out.Width = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson455788a0EncodeWsTermInternalController(out *jwriter.Writer, in WindowSize) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"high\":"
		out.RawString(prefix[1:])
		out.Int(int(in.High))
	}
	{
		const prefix string = ",\"width\":"
		out.RawString(prefix)
		out.Int(int(in.Width))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WindowSize) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson455788a0EncodeWsTermInternalController(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WindowSize) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson455788a0EncodeWsTermInternalController(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WindowSize) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson455788a0DecodeWsTermInternalController(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WindowSize) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson455788a0DecodeWsTermInternalController(l, v)
}
